name: Chess Openings
topic: Value of Openings
path: chess_openings
list_name: Opening List
link: https://www.thechesswebsite.com/chess-openings/
list_cont_id: cb-container
list_cont_nr: 1
list: a
item: h5
